version: '3.8'
services:

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

